### ISSUE TITLE
WebGL device

### ISSUE THREAD

**Issue by slimsag** [azul3d/gfx#40]
For WebGL to be supported by the graphics package we need to:

- [ ] Add support for creating a WebGL canvas on a target HTML element ID (e.g. a div tag), via the `gfx/window` package.
- [ ] Add a WebGL-based renderer.

Moved here from https://github.com/azul3d/issues/issues/29

**Comment by shurcooL** [comment]
We've done some pretty cool things above. :)

It's interesting that I take it for granted now, but this thread shows the progression and how it took collaboration, hard work, and multiple breakthroughs to make today's reality possible. Thanks again for help @slimsag!

**Comment by slimsag** [comment]
:smile: :+1:
