### ISSUE TITLE
transform.SetQuat can panic

### ISSUE THREAD

**Issue by jteeuwen** [azul3d/gfx#90]
`Transform.SeQuat`is missing a nil check before the pointer dereference and can panic as a result:

https://github.com/azul3d/gfx/blob/v2-dev/transform.go#L231:

	func (t *Transform) SetQuat(q lmath.Quat) {
		t.access.Lock()
		if (*t.quat) != q {
			t.built = nil
			t.quat = &q
		}
		t.access.Unlock()
	}

**Comment by slimsag** [comment]
Thank you for the detailed issue report.

I've fixed the issue at hand and added a test to ensure this method works.
